### ISSUE TITLE
请问这个彩虹猫页面是如何加载nyancat.js的？

### ISSUE THREAD

**Issue by Comdex** [TakWolf/NyanCatEverywhere#1]
rt.看了一下index.html没有引用nyancat.js，仅有go()这个js函数出发打开页面的行为，那nyancat.js是什么时候加载到页面中的，js新手好奇求问。。。。

**Comment by TakWolf** [comment]
效果页面加载并不在index中，而在不同的子页面加载
例如：nyancat.html

这个页面中包含两个js，include.js创建一个iframe元素，nyancat.js则是实际的效果

include.js会监听url锚点的变化，来改变iframe的引用，例如
[http://nyan.takwolf.com/nyancat#http://blog.takwolf.com](http://nyan.takwolf.com/nyancat#http://blog.takwolf.com)

"#"后面部分可以替换为目标页面

index.html仅仅用来做跳转

**Comment by TakWolf** [comment]
你可以忽略掉index.html这个文件，只关注nyancat.html即可

**Comment by Comdex** [comment]
感谢指点，还有疑问的是在index.html没发现引入include.js那它是怎么监听到锚点的变化？window.open这个函数怎么跳转到nyancat.html的？

**Comment by TakWolf** [comment]
window.open这个函数是打开一个新页面

include.js是在nyancat.html中引入的，因此锚点是在nyancat.html中监听的，而不是在index.html中

**Comment by Comdex** [comment]
抱歉，我的意思是window.open是怎么跳到nyancat.html中的?

**Comment by TakWolf** [comment]
button点击的时候会调用go这个函数，会传递一个对应的id进去，然后通过id获取对应input中的url，手动拼接了一下。window.open(url)是一个系统函数，作用是打开一个新页面

**Comment by Comdex** [comment]
十分感谢，我看漏了，原来http://nyan.takwolf.com/nyancat这个地址就表示访问了nyancat.html

**Comment by TakWolf** [comment]
喵~
